AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - context

# Configuration parameters: TreatCommentsAsGroupSeparators, ConsiderPunctuation, Include.
# Include: **/*.gemfile, **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

